version: "3"

networks:
  app-network:

services:
  macecaledon-api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: macecaledon-api
    image: macecaledon-api:latest
    command: python /app/Backend/app.py
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    depends_on:
      - mongo
    environment:
      - API_PORT=8080
      - API_HOSTNAME=0.0.0.0
    networks:
      - app-network

  macecaledon-frontend:
    build:
      context: ./Frontend/mace-frontend
      dockerfile: Dockerfile
    container_name: macecaledon-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - "./Frontend/mace-frontend:/app"
    networks:
      - app-network

  mongo:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongo
    command: mongod --port 8200
    ports:
      - "8200:8200"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

  nginx:
    build:
      context: ./Frontend/mace-frontend/nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - macecaledon-api
      - macecaledon-frontend
      - mongo
    networks:
      - app-network

volumes:
  mongo-data:
