version: "3"

services:
  macecaledon-api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: macecaledon-api
    image: macecaledon-api:latest
    command: python /app/Backend/app.py
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    depends_on:
      - mongo
    environment:
      - API_PORT = 8080
      - API_HOSTNAME = 0.0.0.0

  # Frontend service
  macecaledon-frontend:
    build:
      context: ./Frontend/mace-frontend
      dockerfile: Dockerfile
    container_name: macecaledon-frontend
    ports:
      - "3000:3000"
    volumes:
      - "./Frontend/mace-frontend:/app"

  # MongoDB service
  mongo:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongo
    command: mongod --port 8200
    ports:
      - "8200:8200"
